### ISSUE TITLE
WikiExport fails with 'key not present in dictionary'

### ISSUE THREAD

**Issue by wasowski** [lervag/wiki.vim#116]
I am getting this from WikiExport:
```
Error detected while processing function wiki#page#export:               
line   50:
E716: Key not present in Dictionary: link_ext_replace && l:cfg.ext !=# 'html'
E15: Invalid expression: l:cfg.link_ext_replace && l:cfg.ext !=# 'html'
--self-contained is needed for pandoc to include images in HTML
```

After some reading of the code I figured that it works if one calls it with an option `-link-ext-replace`. This seems create `l:cfg.link_ext_replace` in 
https://github.com/lervag/wiki.vim/blob/ac73b38d5e7500cf24ffcf02d4793dce18b7a409/autoload/wiki/page.vim#L312

This seems to be coming from PR #106. As far as I can see the condition in line 
https://github.com/lervag/wiki.vim/blob/a6e51c7ef5e8520782b570e72598d3344e8d5d97/autoload/wiki/page.vim#L346
needs to be made robust for the case where the config field does not exist, or the config field should be pre-initialized.

BTW. There seems to be no help for `WikiExport` but I am almost sure there used to be one ? (or my installation got borked).

**Comment by lervag** [comment]
>  needs to be made robust for the case where the config field does not exist, or the config field should be pre-initialized.

That's strange; to me it seems this is already fixed by adding the option here:

https://github.com/lervag/wiki.vim/blob/ac73b38d5e7500cf24ffcf02d4793dce18b7a409/plugin/wiki.vim#L26-L30

The `wiki#init#options` should make sure that the defaults are specified unless overridden.

> BTW. There seems to be no help for `WikiExport` but I am almost sure there used to be one ? (or my installation got borked).

Strange. On my side, `:help WikiExport` works as expected?

https://github.com/lervag/wiki.vim/blob/ac73b38d5e7500cf24ffcf02d4793dce18b7a409/doc/wiki.txt#L660

Perhaps you are not on the latest Git revision?

**Comment by wasowski** [comment]
Ooops! You're probably right. I might be on a fork that is a few weeks old. Sorry!

**Comment by lervag** [comment]
No problem, honest mistake :)
