### ISSUE TITLE
Support .md postfix

### ISSUE THREAD

**Issue by BonaBeavis** [lervag/wiki.vim#12]
With this it would be possible to edit github/gitlab wikis locally and in markdown.

**Comment by BonaBeavis** [comment]
No, thanks for sharing your your work! Separating the syntax would be a great idea. There is [ Markdown Vim Mode](https://github.com/plasticboy/vim-markdown) and [Markdown for Vim](https://github.com/gabrielelana/vim-markdown) which could do it.

My main concern is linking, because I think this is the magic which makes wikis so powerful. And creating a link (and a new page) or following a link should be as seamless as possible. 
The perfect workflow would be:

Beginning with:
```markdwon
# Some Header

- A project name
```
Then highlight `A project name` and call a function for creating a link.
Now this function must create a slug from the highlighted text and replace the highlight with a link. 

The problem is, that the slug could be `a-project-name` or `AProjectName` or `a_project_name`, the link format could be `[A project name](a-project-name)` or `[A project name](a-project-name.md)` or `[[A project name|a-project-name]]`.
And having the right link formats and file slugs is very relevant when using the wiki outside of vim. For example this issue, or I had a similar issue when previewing the wiki with a firefox plugin, this plugin could only follow links in a specific format.

If you think, making the generation of slugs and formatting of links configurable, are useful extensions I would like to help to implement this.

**Comment by lervag** [comment]
Exactly, the linking is the magic of wiki's. I think that it would make a lot of sense to decouple the syntax from the plugin, because it would allow that one applies this on top of other plugins for various file types, including normal Markdown, but also other dialects.

Note, however, that it will be some work, and I'm not that free to do things right now. I will come to it sometime, though.

See also #8 and #9. I'm creating new issues as described in #9 now.

In the meantime, you are outlining a new feature. Currently, you can create a link by selecting text and hitting `<cr>` (Enter key). This works, but it always assumes that the link target is the same as the selected text. If I understand you correctly, you are asking that we add a feature where one can apply a map from the selected text to the target link. I think this should be easy to implement, and it should be easy to allow user customization.

I'll open a new issue for this as well, and then close the current issue. I hope that's OK by you.

**Comment by lervag** [comment]
Let me know if #13 describes the desired feature properly, but please continue the discussion of this there.
