### ISSUE TITLE
Loading with packer.nvim

### ISSUE THREAD

**Issue by tramhao** [lervag/wiki.vim#127]
# Description
Loading with packer.nvim works, but the code to modify link doesn't work.

```
    use {'lervag/wiki.vim', 
    config = function ()
            vim.g.wiki_root = "~/Sync/wiki"
            vim.g.wiki_filetypes = {"md"}
            vim.g.wiki_write_on_nav = 1
            vim.api.nvim_exec(
            [[
            
            function MyFunction(text) abort
               return substitute(tolower(a:text), '\s\+', '-', 'g')
            endfunction

            let g:wiki_map_link_create = 'MyFunction'
            ]],
            false)
           end,
    -- ft = 'markdown',
        }

```
It compiles with no error, but when I create links, the text is not modified.

**Comment by lervag** [comment]
I dont know what `packer.nvim` is, I don't know what you mean with "compiles" (wiki.vim does not have any features related to compilation).

If you want me to investigate, then you need to provide a full minimal example and a description that makes it easy for me to reproduce your problem.

Note, I think it should be `vim.g.wiki_filetypes = ["md"]`?

Also note that there should not really be any cost to loading wiki.vim "globally", and it does give a couple of convenient mappings for quickly opening the wiki specified with `g:wiki_root`.

**Comment by tramhao** [comment]
Thanks so much for your reply.
Packer.nvim is from https://github.com/wbthomason/packer.nvim
and it's a package manager in lua. I use it because it can keep the loading of plugin and configuration of this plugin in the same place, so that I could easily comment out a plugin with it's configurations for debug purpose. I have no problem loading wiki.vim globally.
Packer.nvim will compile the plugins into one precompiled file, so if compile is ok, it means that at least the syntax checks are all right.
I'm new to vimscript so please forgive me if it's a dumb question. In the code function MyFunction(text), the text is coming from global variable? It's a such generic name so my search doesn't have any information about it. Thanks.

**Comment by tramhao** [comment]
vim.g.wiki_filetypes = ["md"] raised error for lua.

**Comment by lervag** [comment]
> Thanks so much for your reply.
> Packer.nvim is from https://github.com/wbthomason/packer.nvim
> and it's a package manager in lua. I use it because it can keep the loading of plugin and configuration of this plugin in the same place, so that I could easily comment out a plugin with it's configurations for debug purpose. I have no problem loading wiki.vim globally.
> Packer.nvim will compile the plugins into one precompiled file, so if compile is ok, it means that at least the syntax checks are all right.

Thanks for the explanations.

> I'm new to vimscript so please forgive me if it's a dumb question.

No such thing :)

> In the code function MyFunction(text), the text is coming from global variable?

You mean the argument `text`? No, the point of this function is that it is used by a link parser when transforming text into a link.

By default, the text is converted to a link directly without any transformation, but with this function and the option `g:wiki_map_link_create`, the text will be transformed. E.g., if you visually select the words `THIS IS MY LINK` and convert it to a link with the default map `<cr>` with wiki.vim, then the result should be `[[this is my link|THIS IS MY LINK]]` (you might be interested also in the option `g:wiki_link_target_type = 'md'` to specify markdown style links as the default target).

> vim.g.wiki_filetypes = ["md"] raised error for lua.

Ok, sorry: I don't really know any lua myself. I guess the `{}` is the list syntax in lua, then.

And, since I don't know lua, I also really don't know how to help in fixing your configuration here. I have no idea why the configuration does not work as expected. :\

**Comment by tramhao** [comment]
This problem solved! It's loaded fine and thanks a lot!

**Comment by lervag** [comment]
Great! It would be nice if you could explain what was wrong. My impression is that "nothing was wrong", but then why did things not work? Perhaps the docs are unclear on something?

**Comment by tramhao** [comment]
In my case, the problem is I didn't use the function correctly. I didn't select the text in visual mode, so didn't generate link correctly. Actually the function is defined correctly by vimscript inside lua. Thanks.
