### ISSUE TITLE
[[wiki:<name>]] inside journal's page creates a file under under `journal` when followed

### ISSUE THREAD

**Issue by bybor** [lervag/wiki.vim#152]
I tried `[[journal:<name>]]` syntax before and it worked great, but I didn't know about `[[wiki:<name>]]` until today - I used `[[/<name>]]` because of that.

When I tried to `<Plug>(wiki-link-follow)` on `[[wiki:<name>]]` it created new file under journal's directory. Is it by design/known limitation? I think `wiki.vim` allows to define a custom resolver for cases like this?

**Comment by lervag** [comment]
I can see how this is confusing. The thing is: the link url is defined as `[<scheme>:]<target>`, where the default scheme is `wiki`. So: `[[wiki:page]]` is equivalent to `[[page]]`. And similarly, `[[wiki:/page]]` is equivalent to `[[/page]]`. The leading `/` anchors the target to the wiki root.

The `journal` scheme is simply a convenience scheme that anchors the target to the journal directory. I'm not even sure if it is a good idea, but I do find myself using it. That is, with the default settings, `[[/journal/target]]` is equivalent to `[[journal:target]]`. However, with the journal scheme, you can write the url without using the link syntax. I.e., if you write `journal:2021-05-13`, it will be recognized properly as a journal link even if it is not in the standard wiki link syntax.

So, this is all by design. But I won't claim that the design is perfect, and I'll be open to discussions on this.

**Comment by bybor** [comment]
It makes sense, thanks. It was one of the last "new" things I learnt about vimwiki.

> Interwiki~
> 
> If you maintain more than one wiki, you can create interwiki links between
> them by adding a numbered prefix "wikiX:" in front of a link: >
>   [[wiki1:This is a link]]
> or: >
>   [[wiki1:This is a link source|Description of the link]]

The one and only one wiki works fine for me (plus diary/journal). My first approach was to put everyday notes into diary, and it doesn't work very well. Next thing was to use today's diary as an index for bigger things that deserve separate files/notes. Now, why to keep those files under "diary" folder? That was my reasoning. At this point I discovered [[/<page>]] syntax, which `wiki` supports. And I can try to use custom resolver to override default behavior.

**Comment by lervag** [comment]
Ah, yes: I can see how some people find the concept of multiple wikis with links between the wikis interesting. IMHO, this seems more or less unnecessary. Instead, I try to imagine that wiki.vim should be more or less uninterested in your existing files. Instead, if you open a file within a wiki, it should just work. Of course, I do think having a main wiki easily accessible is valuable, which is why the `g:wiki_root` and `:WikiIndex` and `:WikiJournal` exist. But this is more of an exception and simple, extra functionality, than something fundamental. Also, links between different wiki's can be easily made with file urls, such as `file:/path/to/other/wiki/index.wiki`.

Personally, I use both the wiki and diary excessively. I of course keep all general notes in the wiki directory, and the diary/journal notes under the journal directory. I tend to have a flat structure, so mostly no subdirectories (with a few exceptions).

**Comment by lervag** [comment]
And yes, you can define your own custom resolver to override the default behaviour. It should allow quite abit of customisation, I think.

**Comment by bybor** [comment]
Hey, I understood what you meant by "[[wiki:]] is a default scheme only now when I tried to implement custom resolver :)

This means that I cannot use `g:wiki_resolver` to resolve [[wiki:Current]] as [[/Current]], because the function doesn't receive `url.scheme` as input?

Instead, it should be a custom "scheme", like "[[w:Current]]".

Do I get it right?

**Comment by lervag** [comment]
> Do I get it right?

Yes, precisely. `g:wiki_resolver` is meant to resolve the file path given the input url _without_ the scheme. But you can define your own custom schemes by creating your own `autoload/wiki/url/scheme.vim` file. This is not very well documented, as it is a quite advanced customization. But if you look at the `autoload/wiki/url/*.vim` files as examples, it should not be too hard. The `man.vim` or `vimdoc.vim` may be the simplest examples.

**Comment by bybor** [comment]
I think I found a nice solution to this. If you use only two folders - one for journal and another for everything else, then resolver function could check if the file name follows YYYY-MM-DD pattern and treat it as `journal` link. Everything else should be considered as `root` file.

This should be a user choice/preference (just as you designed it) because it will not fit all. Thank you for pushing me in the right direction.

**Comment by lervag** [comment]
I'm happy to hear you're figuring things out! :)
