### ISSUE TITLE
Create link from visual selection

### ISSUE THREAD

**Issue by sophiabrandt** [lervag/wiki.vim#161]
Is there a way to create a link via `WikiLinkToggle` from a visual selection?

Use case: I use markdown style links. So, for example, if I type:

```md
- Data-Driven Programming
```

then visually select the line, I'd like to have the below outcome (maybe using `wiki_map_link_create` with a function):

```md
- [Data-Driven Programming](Data-Driven_Programming)
```

Thank you for your work.

Edit by @lervag: Fixed `WikiToggleLink` → `WikiLinkToggle`.

**Comment by lervag** [comment]
Yes, this should already work. The standard mapping for `WikiToggleLink` is `<cr>` - aka the enter key. And it is mapped in both visual and normal mode.

Note: The `:WikiLinkToggle` command does not work in visual mode directly, because by typing `:` from visual mode you are actually _exiting_ visual mode. Thus, you need to use the mapping to have this work.

To be more specific, the following mappings are created by default:

```
n  <CR>         @<Plug>(wiki-link-follow)                               
x  <CR>         @<Plug>(wiki-link-toggle-visual)
```

This means that, in normal mode, `<cr>` is mapped to `<plug>(wiki-link-follow)` and in visual mode, `<cr>` is mapped to `<plug>(wiki-link-toggle-visual)`.

I hope this helps, but let me know if you need more assistance.

**Comment by sophiabrandt** [comment]
Ah, sweet, I didn't know that.
Many thanks for the detailed answer. :heart_eyes:

**Comment by lervag** [comment]
Glad it helps :)
