### ISSUE TITLE
Linking filename that contains closing parenthesis

### ISSUE THREAD

**Issue by protist** [lervag/wiki.vim#164]
# Description

How should we link files/paths with a closing parenthesis in the file name? I would like to use `[name](link)`, but the closing parenthesis is interpreted as part of the format itself, and not the file name.

# Minimal working example

Let's assume I want to link to a file named `file (parens).md`

`[link](file (parens))` doesn't work. When I attempt to follow the link, it misses the final `)`, i.e. it links to `file (parens.md`

I've also tried:
1. escaping the paren(s) with `\` -> doesn't even parse as a link.
2. enclosing the path in `<...>` -> interprets the first `<` literally, then cuts off the last `)` anyway.
3. quoting the path with `"` -> interprets the first `"` literally, then cuts off the last `)` anyway.

The only format I could find that works is `[[file (parens)|link]]`, but I would prefer not to use this format, because (a) I don't love the syntax, and (b) the vim plug-ins don't elide this form.

**Comment by lervag** [comment]
This is a hard problem, actually. Since the markdown link uses parentheses, it becomes near to impossible to properly parse link urls that may contain parantheses by use of regexes.

Consider these two examples:

```markdown
1. Here is a [link to a file with parens](file (parens)).
2. Here is a ([link to a file _inside_ parens](another file)).
```

With regexes, there is no way to "count" the parantheses level, so we must either match _all_ or 1.

I could envision using an advanced "algorithm" that continuosly tests the matched url if it is valid, but that seems like a black hole of trouble.

So, I'm sorry to say that I don't really know a good solution and I would ask if you could manage without parantheses in your filenames. Not perfect or optimal, but perhaps a manageable compromise?

Unless you (or anyone else) happen to have a good idea, of course!

**Comment by protist** [comment]
Thanks again @lervag. No worries at all. I'm actually attempting to transition from an old vimwiki system to a new markdown/wiki.vim structure. IMO having the parens in filenames is a bit weird anyway, so I'm happy to transition to something simpler.

**Comment by lervag** [comment]
> Thanks again @lervag. No worries at all. I'm actually attempting to transition from an old vimwiki system to a new markdown/wiki.vim structure. IMO having the parens in filenames is a bit weird anyway, so I'm happy to transition to something simpler.

Great, thanks!
