### ISSUE TITLE
Error when opening file newer than swap file as read-only

### ISSUE THREAD

**Issue by C-Fergus** [lervag/wiki.vim#166]
## Description

After updating to the latest version to test templates I did the following:

1. Edit a wiki page with a swap file outside of vim
2. Attempt to open the wiki page in vim and get a message noting the file is newer than the swap file
3. Open as read-only
4. Results in the following error message:
```
Error detected while processing function wiki#link#follow[13]..function wiki#link#follow[6]..1:

E325: ATTENTION
```

This isn't a critical issue as the error seems to be ignorable.

## vimrc

I don't have any other navigation plugins installed.

[//]: # (The file contents should of course also be included if necessary. Please also)
[//]: # (provide a minimal vimrc file, e.g.)

```vim
set nocompatible

filetype plugin indent on
syntax enable

let g:wiki_root=$HOME . '/Documents/notes'

let g:wiki_global_load=0
let g:wiki_filetypes=['rmd', 'markdown', 'pandoc', 'wiki']
let g:wiki_link_extension='.rmd'
let g:wiki_link_target_type='md'
let g:wiki_write_on_nav=1
```

**Comment by lervag** [comment]
Hmm, strange. I can't reproduce this. I tried the following:

Minimal vimrc:

```vim
set nocompatible
let &rtp = '../../../,' . &rtp
filetype plugin indent on
syntax enable

let g:wiki_write_on_nav=1
```

Steps:

1. Created the minimal vimrc (`test.vim`)
2. Added a minimal index.wiki
3. Opened index.wiki with `vim -u test.vim index.wiki`
4. While it is open, I copied the `.index.wiki.swp` file.
5. Closed Vim.
6. Edited the file in a different editor, then copied back the old swap file.
7. Opened index.wiki again; there is no error.

I also tried with a second file `test.wiki` where instead of opening it directly, I opened by following a link. Still couldn't reproduce.

I'm on Vim version 8.2 with patch level 2891. Not sure if that matters.

**Comment by C-Fergus** [comment]
I am on 8.2, 2845. I haven't had the time to check this further and probably won't for another while. If you can't reproduce it then it might well be something else I have set or added. I had a crash a little before the error happened which would explain the E325 better than editing in another program, odd that you didn't get one for your "anomalous" swap file.

Although looking at the documentatoin, E325 shouldn't occur if the file is newer than the swap file. Possibly what I thought was my crashed instance of vim was actually still running when I attempted to edit the second time causing E325 which then may have led to the `wiki#link#follow` error upon opening the file as read only.

**Comment by lervag** [comment]
I believe I've fixed it now. :)
