### ISSUE TITLE
Fix file scheme handler to respect g:wiki_viewer

### ISSUE THREAD

**Issue by lervag** [lervag/wiki.vim#171]
The file handler/follower function does not properly respect the `g:wiki_viewer` default key `_`:

https://github.com/lervag/wiki.vim/blob/871e55ec2e9599732567a3166abb777f7fff7581/autoload/wiki/url/file.vim#L37-L41

The documentation for `:help g:wiki_viewer` implies that the `_` key specifies a default viewer that is used if a specific viewer for a specific file type is not defined.

Suggested solution: Update `s:handler.follow` in `url/file.vim` to respect the `g:wiki_viewer['_']` key.

**Comment by lervag** [comment]
I believe this should be resolved now. Please test.

**Comment by protist** [comment]
@lervag I've tested and can confirm it's working now. Thanks again for the super quick fix!

**Comment by protist** [comment]
Sorry @lervag. I tested a bit more, and it looks like I get some slightly inconsistent behaviour. For example, I tested a link to `[foo](file:~/bar.md)`. This works perfectly if it opens within vim (i.e. goes through the conditional as per [this thread](https://github.com/lervag/wiki.vim/issues/165#issuecomment-875093444) then `execute 'edit' self.path`). However, if I change the conditional so that it passes by and uses `g:wiki_viewer` instead, I get an error from `xdg-open` saying that the file does not exist.

I'm not sure if it's a quoting issue, because if I change the path from `~/bar.md` to `/home/protist/bar.md`, it works fine. Perhaps the `~` is not being expanded?

**Comment by lervag** [comment]
Sorry, try now.

**Comment by protist** [comment]
Thanks @lervag. Works perfectly now. Thank you again for the great work!

**Comment by lervag** [comment]
Great, glad to hear it! :)

**Comment by protist** [comment]
Sorry @lervag I found another bug (unless it's a feature?). Directories seem to open in the current instance of vim, whereas I would have expected them to open with `xdg-open`. I tested with and without the trailing slash:

* `[foo](file:/path/to/dir)`: this opens in vim's directory viewer, similar to running `vim /path/to/dir`
* `[foo](file:/path/to/dir/)`: this looks like it creates a new empty document, but the status line says `"/path/to/dir" is a directory`. Attempting to modify and save the file fails and gives `E502: "/path/to/dir" is a directory`

**Comment by lervag** [comment]
> Sorry @lervag I found another bug (unless it's a feature?). Directories seem to open in the current instance of vim, whereas I would have expected them to open with `xdg-open`.

Strange; this works as expected for me in both of the examples, with and without the last slash. Could you open a new issue and provide the full details (i.e. your relevant config)?

**Comment by protist** [comment]
Oops, sorry @lervag, I got confused. I was running the stable version on one system, and the development version on another. The latest version works fine for directories. Sorry for the noise!

**Comment by lervag** [comment]
No problem :)
