### ISSUE TITLE
https scheme not supported in Windows

### ISSUE THREAD

**Issue by BirgerNi** [lervag/wiki.vim#214]
The following markdown-link works on my fedora machine:

```vim
[google](https://google.com)
```

However, it does not work on my windows machine. Maybe on windows I have to set a variable like `g:wiki_viewer` but that is not fully clear from the manual.

**Comment by lervag** [comment]
> The following markdown-link works on my fedora machine:
> 
> ```viml
> [google](https://google.com)
> ```

wiki.vim refers to this link as a markdown-type link. But the problem here is not with the link, but with the url and how it is handled. The url has a scheme `https:` which is not handled internally, but is recognized as a "generic" scheme. The generic handler uses the `g:wiki_viewer` variable to determine how to open the link. On Linux, the default handler is `xdg_open`, which usually "just works". However, on Windows, the default handler is undefined. This again explains why it does not work.

I believe these concepts are quite well explained in the documents, although there is probably room for improvement. The relevant section is `:help wiki-link-url` - feel free to specify where it is lacking and/or suggest improvements by PR.

> However, it does not work on my windows machine. Maybe on windows I have to set a variable like `g:wiki_viewer` but that is not fully clear from the manual.

Precisely. However, before I continue, please note that I do not really plan to support Windows. With that, I mean that if there are significant hurdles I may not wish to address them. But in this case, I hope that this should be sufficient:

```vim
let g:wiki_viewer = {'_': 'start'}
```

If it is, then I may add it as the default for Windows.

**Comment by BirgerNi** [comment]
> Precisely. However, before I continue, please note that I do not really plan to support Windows.

Fair enough. Another reason to switch to mac at work ;-)

The setting `let g:wiki_viewer = {'_': 'start'}` just open a terminal. The following commands work, maybe that helps:

```markdown
:call system('start https://google.com')
:call system('cmd /c "start https://google.com"')
:call system('cmd /c "rundll32 url.dll,FileProtocolHandler https://google.com"')
```

When the cursor is over the URL the command `gx` work as well. According to the docs `gx` use the Windows FileProtocolHandler. Maybe `wiki.vim` could use a wrapper around `gx` instead of launching a shell command and let `gx` do all the (shell-)escaping?

**Comment by BirgerNi** [comment]
The command `gx` uses the `netrw` plugin and calls `netrw#BrowseX`. The following code works for me:

```rmarkdown
# open rmarkdown link in RStudio
call netrw#BrowseX("new_file.Rmd", 0)

# open URL in default browser
call netrw#BrowseX("https://google.com", 0) 

# open test.pdf in default pdf reader
call netrw#BrowseX("test.pdf", 0)
```

The `netrw` plugin is already integrated in Vim and seems to handle external files well. The `wiki.vim` plugin could focus on extracting the URL out of the markdown link and just pass the URL to netrw. What do you think?

**Comment by lervag** [comment]
> Fair enough. Another reason to switch to mac at work ;-)

:)

(Or to Linux?)

> The setting `let g:wiki_viewer = {'_': 'start'}` just open a terminal. The following commands work, maybe that helps:

Thanks for testing. I'm a little bit surprised that the `'start'` value in the option did not work when `system('start ...')` did... can you try to use `let g:wiki_viewer = {'_': ''}`?

> The command `gx` uses the `netrw` plugin and calls `netrw#BrowseX`. The following code works for me:

Interesting! I believe this may be a very good suggestion! I've added it now for the generic url handler with a fallback to the old behaviour. Can you update and test if this makes things work on your end?

**Comment by BirgerNi** [comment]
> Thanks for testing. I'm a little bit surprised that the 'start' value in the option did not work when system('start ...') did... can you try to use let g:wiki_viewer = {'_': ''}?

That solution does not work. A terminal (?) window pops up on task bar and thats it.

> I've added it now for the generic url handler with a fallback to the old behaviour. Can you update and test if this makes things work on your end?

That work like a charm. Thank you.

**Comment by lervag** [comment]
Glad to hear it! :)
