### ISSUE TITLE
Opening wiki changes the working directory.

### ISSUE THREAD

**Issue by typhooncamel** [lervag/wiki.vim#23]
When I open the wiki from a session I'm currently working on, edit a wiki file, and quit the buffer, the working directory is changed. E.g.:

* open `~/test.py` in neovim, edit, so current directory is `~/`;
* open wiki (located in `~/documents/diary`) with `<leader>ww`, edit wiki, exit buffer;
* return to `~/test.py`. The working directory is now `~/documents/diary` (i.e., it never changed back to `~/`, which I would have thought would be the more intuitive behaviour).

**Comment by lervag** [comment]
Strange. I've tried to reproduce with no luck. I've pushed my test files to the repo, see `test/issues/23`. I do:

1. `nvim -u minivimrc`. This opens `test.py` with neovim (should work with Vim as well).
2. Do `<leader>ww` to open the example wiki index. The current path has not changed.
3. Do `:bwipe` to kill the wiki buffer and return to the `test.py` buffer. Still, the path is as expected.

Could you provide the configuration that is relevant in order to reproduce your problem?

**Comment by typhooncamel** [comment]
I'm really sorry, you're right, I should've checked with a minimal configuration. That's true - in that case the path does not change. For some reason (I can only guess it's something else in my configuration), with my setup it does change, which is a bit annoying. I'll try to figure it out. Thanks for your response! And great work on the plugin.

**Comment by lervag** [comment]
> And great work on the plugin.

Thanks! I'm happy it is useful to others as well as myself.

Note: The `autochdir` option could look relevant here. But it is not enough to add it to reproduce your problem. I suspect that there is some conflict with another plugin or with some of your settings.

I propose that you attempt to make a detailed step-by-step list of instructions to produce your problem. Then strip down your vimrc file (e.g. bisect by commenting out half and half of your content) in order to find the relevant settings/plugins.

**Comment by typhooncamel** [comment]
I eventually figured out the problem. It involves the [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc) plugin, which I suspect some people using `wiki.vim` might also use. The plugin automatically enables a `CHDIR` option (see `vim-pandoc-chdir-module`) which "changes the current window directory to the one the file is in". This needs to be disabled.

**Comment by lervag** [comment]
Ah, I see. At a first glance, it strikes me as a strange option, since Vim already has the `'autochdir'` option. In any case, I'm happy to see the issue resolved.
