### ISSUE TITLE
[Feature Request] Enable wiki.vim handles separate journal directory

### ISSUE THREAD

**Issue by mizhozan** [lervag/wiki.vim#273]
First, can we have a separate directory? like

```vim
let g:wiki_root = ['~/Work/Notes', '~/Another/path/Notes', '~/Journals']
let g:wiki_filetypes = ['md',  'wiki']
let g:wiki_link_extension = '.md'
let g:wiki_global_load = 0
let g:wiki_link_target_type = 'md'
let g:wiki_journal = {
          \ 'name': '~/Journals',
          \ 'frequency': 'daily',
          \}
```

I have maintained a Journal directory for years; a separate Journal dir is better for me. I also don't want to overwhelm note searches with those usually useless journal files. I can use `wiki.vim` exclusively for my primary notes and forget about journals or create a symlink in the primary note if I want to combine the two. But it's beneficial having two separated.

### Possible Solution

With multi-root support, in a minimalistic scenario:
- We designate a separate daily journal (or calendar) directory. Users can define any path as their journal directory. The default value would be the same as the current (relative to the first note directory). I think only journal-related functions like calculating next week or opening a daily journal would be affected.
- All goodies of the wiki.vim like <CR> for creating a **local link** is enabled on all given directories if not enabled globally for all markdown files (like config example above).
- `wiki.vim` when creating a new link, it only considers the current note directory, i.e., it acts like there is one single root directory and is quite similar to the current situation. So if it operates on `NoteDir1/a_note.md`, it acts like a single root with note `NoteDir1` as the only root directory. Close to the current implementation.
- For the **cross-link** situation, unlike vimwiki multi-root that combine all root directories, wiki.vim can safely ignore the notion of cross-links. Those cross-links can be handled with an absolute path. We might imagine some helper function as well. I have a simple `fzf` based command associated with a vimkey that shows me the notes in other/any directory and creates a markdown link with an absolute path out of it. Having two separate note directory kind of means separation of concern as well so cross-link is an exception.

**Comment by lervag** [comment]
I think we should not mix the feature request of a) separating journal path from wiki with b) supporting multiple wiki roots.

I've previously denied requets for multiple wiki roots because I don't quite see any good reasons to add it. The `g:wiki_root` is really _only_ used for a global convenience mapping/command to open one specific wiki/journal. If you need more mappings for this kind of things, then it is trivial to make them yourself. If you feel that we should spend more time on the discussion of multiple wiki roots, then please open a new issue for that - but in fact, I'm more inclined to _remove_ `g:wiki_root` and explain how people can create their own mappings/commands to open some standard wiki. I want us to use this issue for discussing and working on the journal path request. I hope you don't mind!

I will address the issue in #272 before I start working on the journal path. I think you are not far from right in noticing which features are affected by the proposed change, but I think it is a bit more complicated because there are some assumptions in the initialization on the current structure. We may need to make some breaking changes here, e.g. in the behaviour of the standard normal mode `<cr>` mapping inside the journal (which now will make a rooted link, a concept that may not be the same after making these changes). I think the correct approach here is to agree on the documentation first, as that will be a specification of where we want to go with this.

As such, I hope you will find a way to make things work well enough in the mean time!

**Comment by mizhozan** [comment]
Sorry for my confusion, I actually personally don't have multi-root, I only maintain one note directory. What I wanted was to have a separate journal directory as you pointed. So, I think the confusion comes from my assumption that supporting this is the same thing as supporting multi-root until you pointed it out. Anyway, I agree on all your points. 

Regarding the compatibility what I originally thought was a new setting that on default just follow current, so something like this:

```vim
let g:wiki_journal = {
          \ 'journal_root: '/home/user/Documents',
          \ 'name': 'Journals',
          \ 'frequency': 'daily',
          \}
 ```
 
 if `journal_root` not set, then it will assume the current note_dir (like current state). If set, then when it work with journal then it append that `journal_root`. Of course there are detail I don't understand and not know the code base, but just sharing...

**Comment by lervag** [comment]
I've tried to implement this now. The option is called `g:wiki_journal.root` and is documented. Please test! There may still be bugs, but I dont think there are any large ones.

**Comment by mizhozan** [comment]
Thanks, that's awesome! I just test it and didn't find any issue. It works as expected.

**Comment by lervag** [comment]
Great, glad to hear it! :)
