### ISSUE TITLE
Question regarding resolving markdown links in a hierachy structured wiki

### ISSUE THREAD

**Issue by PhilippFeO** [lervag/wiki.vim#290]
Hey lervag,

I've read in the docs that your wiki consists of files in one directory, the `g:wiki_root` directory. Sadly, my wiki is (or will be) structured hierarchical. This leads to the problem that following links doesn't work as I imagined.

Let's assume the following layout:
```
g:wiki_root/index.md
g:wiki_root/Linux
g:wiki_root/Linux/vim.md
```
It is possible to link `vim.md` in `index.md` as expected, i. e. `[vim](Linux/vim.md)`. From my observation, the resolving works by appending the path within `(…)` to the path of the *current* file, i.e. `g:wiki_root` (current file is `index.md`). So, `g:wiki_root/Linux/vim.md` is displayed.

Now, the trouble with my hierarchy begins. Let's pretend I am working in `vim.md` and want to link to `index.md` (or any other file outside of `Linux/`). I type `[index](index.md)`, hit `<CR>` and a new buffer with the path [^1] `Linux/index.md` is opened and not the desired `g:wiki_root/index.md`.

[^1]: Not sure, whether it's technically correct to say that buffers can have paths.

--- 

Do I understand this behavior correctly?

Next (obvious) question: Do you have any advice in mind? I've read #231 but it doesn't fit my usecase. I also didn't stumble across an option in the docs where I can modify the mechanics of `<plug>(wiki-link-follow)`.
The only solution I have in mind so far is renaming all files with the scheme `{mock path}-{file}.md` (in the above example `Linux-vim.md`) and place them under `g:wiki_root`.

**Comment by lervag** [comment]
> I've read in the docs that your wiki consists of files in one directory, the `g:wiki_root` directory. Sadly, my wiki is (or will be) structured hierarchical.

Why "sadly"? You are free to structure things the way you want. But I do actually recommend to avoid strict hierarchies. There are several reasons, but the two most important ones:

1. Strive for simplicity. Flat hierarchies are good because they are simple.

2. Structured hierarchies impose categories. That's fine, but: it is very easy to mis-categorize!
> 
> Let's assume the following layout:
> 
> ```
> g:wiki_root/index.md
> g:wiki_root/Linux
> g:wiki_root/Linux/vim.md
> ```

Notice that Vim does not fit under Linux as a category, ref my point 2 above. :)

> Now, the trouble with my hierarchy begins. Let's pretend I am working in `vim.md` and want to link to `index.md` (or any other file outside of `Linux/`). I type `[index](index.md)`, hit `<CR>` and a new buffer with the path [1](#user-content-fn-1-159735296e3263c91de508f891c21bd5) `Linux/index.md` is opened and not the desired `g:wiki_root/index.md`.
> 
> Do I understand this behavior correctly?

Yes. You have three choices:

* `[root index](/index.md)` This links to the `index.md` at the wiki root.
* `[below index](../index.md)` This links to the `index.md` at the sub directory.
* You can implement your own resolver, see `:help g:wiki_resolver`. This is an advanced option and may not be what you should do unless you want to learn to write Vimscript or Lua.

> Next (obvious) question: Do you have any advice in mind?

Did you read my "guide" in the docs, `:help wiki-intro-guide`? I believe it has several, IMHO good, advices.

> The only solution I have in mind so far is renaming all files with the scheme `{mock path}-{file}.md` (in the above example `Linux-vim.md`) and place them under `g:wiki_root`.

Yes, this is one way to do things. But I believe I've explained the alternatives above. Let me know if I may have been unclear or if you still have questions.

By the way, you may want to be aware of #289, as it will probably affect you.

> Not sure, whether it's technically correct to say that buffers can have paths. [leftwards_arrow_with_hook](#user-content-fnref-1-159735296e3263c91de508f891c21bd5)

Buffers "represent" files. They do not need to be existing files, but they usually represent a file on your system, and such files have a path. Thus, it is not quite wrong to say that buffers have a path. And it is perfectly correct to say that buffers _can_ have paths.
