### ISSUE TITLE
Cannot get completion to work

### ISSUE THREAD

**Issue by iexos** [lervag/wiki.vim#307]
# Description

I want to use the completion to find pages and cannot get it to work. I boiled it down to the absolut minimum, what am I missing?

* `vim -u ~/junkyard/init.vim ~/junkyard/index.md`
* start typing `tes` (or `[tes` or `[x](tes`,...) and press `C-X C-O`
* expecting completion for `test.md` but nothing happens

# Notes
* `:WikiPages`, `<cr>` and other functionality works as expected
* `C-X C-O` works for e.g. python with this `init.vim`
* `:verbose set omnifunc?`: `omnifunc=wiki#complete#omnicomplete   Last set from ~/.local/share/nvim/plugged/wiki.vim/autoload/wiki/buffer.vim line 11`

# Minimal working example

Files:
```
$ ls ~/junkyard/wiki
index.md  test.md
```

neovim: NVIM v0.9.0

minimal init.vim:

```vim
let &rtp  = '~/.local/share/nvim/plugged/wiki.vim,' . &rtp
let g:wiki_root = '~/junkyard/wiki'
```

**Comment by lervag** [comment]
> I want to use the completion to find pages and cannot get it to work. I boiled it down to the absolut minimum, what am I missing?

Thanks, this is a very good minimal example! Here are some adjustments to simplify:

* Create test folder:

    ```sh
    mkdir ~/test
    cd ~/test
    touch {index,foo,bar}.md
    ```

* Create `test.vim`:

    ```viml
    let &rtp  = '~/.local/share/nvim/plugged/wiki.vim,' . &rtp
    ```

* Use `nvim --clean -u test.vim index.md` to start neovim

* Type `[test](` then `<c-x><c-o>` and it should complete as expected. This works on my end.

The main change here is that we removed the global `g:wiki_journal`. I believe it is not really relevant here. Does the above work for you?

**Comment by iexos** [comment]
Thank you for the instructions! No, I just get
```
-- Omni completion (^O^N^P) Pattern not found
```

**Comment by lervag** [comment]
> Thank you for the instructions! No, I just get
> 
> ```
> -- Omni completion (^O^N^P) Pattern not found
> ```

That's strange. Which OS are you on? Which version of wiki.vim? If you are not on the latest version, then please update.

After following the steps outlined in my previuos comment, please do this and report the output:

```sh
cd ~/test
pwd   # does your $HOME have strange characters?
ls -l # or tree if you have it
cat test.vim
cat index.md
```

Next, do `nvim --clean -u test.vim index.md` and report the output of:

* `:echo b:wiki`
* `:echo &omnifunc`

**Comment by iexos** [comment]
I'm on a current Arch Linux

```
$ cd ~/.local/share/nvim/plugged/wiki.vim
$ git rev-parse HEAD
f9769a61bfb70ba0801b79174ed7f2f4d31fdf83
$ cd ~/test
$ pwd
/home/holger/test
$ ls -l
-rw-r--r-- 1 holger holger  0 May 25 09:39 bar.md
-rw-r--r-- 1 holger holger  0 May 25 09:39 foo.md
-rw-r--r-- 1 holger holger  0 May 25 09:39 index.md
-rw-r--r-- 1 holger holger 59 May 25 09:39 test.vim
$ nvim --clean -u test.vim index.md
$$ :echo b:wiki
{'root': '/home/holger/test', 'in_journal': 0, 'index_name': 'index', 'extension': 'md'}
$$ :echo &omnifunc
wiki#complete#omnicomplete
```

**Comment by lervag** [comment]
Please also `cat test.vim`.

**Comment by lervag** [comment]
But, it seems things look correct. I want to see `cat test.vim` just to be 100% sure there is no surprise misunderstanding.

The next step is to continue the steps earlier defined steps. After `nvim --clean -u test.vim index.md`, write `[text here](` and then `<c-x><c-o>` - does it still say "Pattern not found"? (I assume it does, since we did not change anything yet.)

Now, perhaps can we do some simple print debugging together. Let's start here:

https://github.com/lervag/wiki.vim/blob/f9769a61bfb70ba0801b79174ed7f2f4d31fdf83/autoload/wiki/complete.vim#L138-L139

Add a line `unsilent echom "DEBUG HERE" l:cnum` before line 139; repeat the test. What is the output? You might need to do `:messages` to see the message after you get "Pattern not found".

I would _expect_ `l:cnum` to be a positive number. If it is, then the next position we want to inspect is here:

https://github.com/lervag/wiki.vim/blob/f9769a61bfb70ba0801b79174ed7f2f4d31fdf83/autoload/wiki/complete.vim#L89-L93

**Comment by iexos** [comment]
Ok, I debugged a bit further and found that `fd` tries to be smart by reading the `.gitignore` in my home dir which excludes everything but a few versioned config files. Simply replacing `fd` with `fd -I` makes completion work.

https://github.com/lervag/wiki.vim/blob/f9769a61bfb70ba0801b79174ed7f2f4d31fdf83/autoload/wiki/complete.vim#LL117C8-L117C8

**Comment by lervag** [comment]
Oh, I did not think of that. Thanks! I'll push an update immediately!

**Comment by iexos** [comment]
Fix works, thank you!

**Comment by lervag** [comment]
Great, glad to hear it! Thanks for digging in and noticing the issue!
