### ISSUE TITLE
`wiki#link#get_creator` having issues retrieving `l:ft` from `g:wiki_link_creation` despite `l:ft` existing in the list.

### ISSUE THREAD

**Issue by daneorie** [lervag/wiki.vim#326]
# Description

When trying to use `:WikiLinkFollow`, `:WikiLinkTransform`, or anything that requires `wiki#link#get_creator`, I get the below error:
```
Error detected while processing function wiki#link#follow[7]..25[1]..wiki#link#templates#word[4]..wiki#link#get_creator:
line    5:
E716: Key not present in Dictionary: "_)"
E116: Invalid arguments for function get
```

In my wiki.vim settings (defined in lua), I currently define a table for `g.wiki_link_creation` with a single entry for `md` that has worked well for me in the past. I'm not sure what changed, but I am now receiving the above error.

I tried looking through the code a bit to see if I could decipher where the issue lies, and I think this function is having an issue with retrieving `l:ft` from the list `g:wiki_link_creation`. I'm sure it's somehow a problem with my setup, but I'm not sure what has changed.
```vim
   function! wiki#link#get_creator(...) abort " {{{1
1.   let l:ft = expand('%:e')
2.   if empty(l:ft) || index(g:wiki_filetypes, l:ft) < 0
3.     let l:ft = g:wiki_filetypes[0]
4.   endif
5.   let l:c = get(g:wiki_link_creation, l:ft, g:wiki_link_creation._)
" line (5) appears to be the failing line, it can't find `l:ft` in the `g:wiki_link_creation` map,
"   so it tries to default to `g:wiki_link_creation._` which is not defined in my list. My understanding
"   though is that my definition shouldn't overwrite any defaults, which I assume would include `_`.
6. 
7.   return a:0 > 0 ? l:c[a:1] : l:c
   endfunction
```

If I modify the code a bit and add some output statements after line (4):
```vim
echo l:ft
" returns `md`

echo g:wiki_link_creation.md
" returns `{'url_transform': function('<lambda>7'), 'url_extension': '.md', 'link_type': 'md'}
```
I'm not sure why line (5) is having issues getting the value from the list if I can directly access that value in the list with the `echo` line.

Any ideas?

**Comment by lervag** [comment]
The problem is most likely in your configuration. I tried to figure it out by inspecting your dotfiles (https://github.com/daneorie/dotfiles). My first question here is: How does wiki.lua get sourced? I noticed you have a branch for switching to lazy where you load wiki.vim configuration here: https://github.com/daneorie/dotfiles/blob/convert-to-lazy/nvim/lua/config/wiki.lua. Is this the config you are currently using?

**Comment by lervag** [comment]
To be more clear on the specific problem here: The function you are looking at assumes that `g:wiki_link_creation` has a `_` key, which is the _default_ filetype that is used if the extension is not recognized. wiki.vim will define this, but if you for some reason override the option instead of defining the option before wiki.vim is loaded, then the default will not be created. That is, the source order here is important. My current suspicion is that [this initialization code in wiki.vim](https://github.com/lervag/wiki.vim/blob/65b67f3669a0db078dab2750d3c51c680ee14df1/plugin/wiki.vim#L47-L64) is sourced _before_ your configuration is applied.

You can easily verify this. After opening a page in the wiki, what is the output of `:echo g:wiki_link_creation`?

**Comment by daneorie** [comment]
Yep, you are correct in your assessment. This is definitely an issue with how—or, rather, when—my configuration is being applied. I'll have to mess around a bit with where to put it. I appreciate you checking it out! Thanks!

**Comment by lervag** [comment]
My pleasure. Let me know if you have further or other problems :)
