### ISSUE TITLE
Discussion: img-clip.nvim

### ISSUE THREAD

**Issue by Traap** [lervag/wiki.vim#331]
Greetings Karl,

Feel free to close this issue.  I am simply using it as a communication thread.

I posted [img-clip.nvim](https://www.youtube.com/watchv=4crDKASq9Nc&t=1s) on YouTube a few days ago.  

I rely on wiki.vim in all my videos.  Presently I am configuring  [wezterm](https://wezfurlong.org/wezterm/) with a goal of merging TMUX features I use into the wezterm configuration.  I am attempting to eliminate tmux-runner and tmux-navigator while maintaining CTRL-[h, j, k, l] to navigate between wezterm splits and neovim splits.

I will then turn my attention to wiki.vim.

I want to show off some of the features I have been using.  Multiple wikies, expanded file types to support programming languages, pandoc, journaling, etc.  

Let me know if there are topic you would like covered.

-Cheers Gary

**Comment by lervag** [comment]
> Greetings Karl,
> 
> Feel free to close this issue. I am simply using it as a communication thread.

Will do; I don't mind using issue threads for communication. Although, perhaps I should enable the Discussions feature on GitHub? I've not used that before, and it may be better for this kind of thing? Do you have experience with it?

> I posted [img-clip.nvim](https://www.youtube.com/watchv=4crDKASq9Nc&t=1s) on YouTube a few days ago.

Yes, I already saw it. Great video! I noticed img-clip.nvim on Reddit and was already planning on trying it out. Your video convinced me to go forward and made it easier. Thanks!

> I rely on wiki.vim in all my videos. Presently I am configuring [wezterm](https://wezfurlong.org/wezterm/) with a goal of merging TMUX features I use into the wezterm configuration. I am attempting to eliminate tmux-runner and tmux-navigator while maintaining CTRL-[h, j, k, l] to navigate between wezterm splits and neovim splits.

Cool! I've looked into wezterm, but I have a strange issue on my side where a bug or problem with xrandr makes startup time for wezterm way too large (https://github.com/wez/wezterm/issues/2339). I use rxvt-unicode myself and I find it to be a very good and very fast terminal. However, it _does_ lack some modern features. If I figured out how to resolve my issue with wezterm I could see myself using it in the future.

> I will then turn my attention to wiki.vim.
> 
> I want to show off some of the features I have been using. Multiple wikies, expanded file types to support programming languages, pandoc, journaling, etc.
> 
> Let me know if there are topic you would like covered.

I find the separation of concerns in wiki.vim to be important, i.e. that wiki.vim _mainly_ handles links between content. It is not a filetype plugin or similar, so you are free to use it with any Markdown plugin or other filetypes. And I've tried to improve things over time so that wiki.vim should be quite flexible with regard to how users want it to behave. All in all, I believe the most important topic may be how wiki.vim handles links. And I think it can be worth mentioning my writeup on how I personally use `wiki.vim` (`:help wiki-intro-guide`), because I think I do raise some valid key points of keeping a good personal knowledge base/wiki (regardless of tool, really).

I think a lot of users may not be aware of the graph features such as `:WikiGraphCheckOrphans` or `:WikiGraphIn`. I find these very useful (when I need them).

Finally, I think the templating feature is interesting. Combined with snippets (from other plugins), it can make it quite a lot quicker to write new notes.

I hope this was the kind of input you wanted?

**Comment by Traap** [comment]
> Will do; I don't mind using issue threads for communication. Although, perhaps I should enable the Discussions feature on GitHub? I've not used that before, and it may be better for this kind of thing? Do you have experience with it?

Yes.  wezterm and lazyvim both have discussion.  It is helpful to have discussions located near source code.

> Yes, I already saw it. Great video!
Thanks.

> I hope this was the kind of input you wanted?
Yes.  This information will help.
