### ISSUE TITLE
`index.md` for Jekyll causes `wiki.vim` to think it's a root

### ISSUE THREAD

**Issue by aldur** [lervag/wiki.vim#387]
First of all: thank you for such a pleasant plugin!

# Description

This puzzled me for a bit before I figured it out. Every time I was editing Jekyll websites, `:WikiJournal` would create a new journal folder in the Jekyll root, instead of opening my usual journal.

I took a look at the code and the issue is related to [this](https://github.com/lervag/wiki.vim/blob/854b1472e2867035bd15d55a0b4d523f5662e242/autoload/wiki.vim#L18). 

As the title states, Jekyll websites typically include a `index.md` file. `wiki.vim` sees the `index.md` file, think it marks a Wiki root, and creates the journal there. (I have configured `md` as my wiki extension).

I'd usually submit this as a PR, but what's the best approach here? Ignore the directory if there's also `_config.yaml`? 

# Minimal working example

Cloning any Jekyll template (e.g. [this one](https://github.com/MichaelCurrin/jekyll-themed-site-quickstart)), starting vim inside it, then using `WikiJournal`.

If helpful I can provide my wiki config or come up with a minimal example.

**Comment by lervag** [comment]
First, you might be interested in the `g:wiki_global_load`. It should resolve your issue, although it would disable wiki.vim outside your `g:wiki_root` wiki.

Now, I think we might want to consider this somewhat closer. I realize from your issue that it would make sense to load wiki.vim similar to the current default settings, but still let e.g. `:WikiJournal` navigate to your configured wiki/journal.

**Comment by lervag** [comment]
> First of all: thank you for such a pleasant plugin!

**Comment by aldur** [comment]
Thank you for the prompt answer! I'll try to collect my thoughts here before answering inline to your comments.

Here's how I use `wiki.vim` (and I realize different users will do it differently). Sometimes, as I am coding/writing, I'll want to quickly take journal notes, or use the journal as a dated scratchpad. For that, I use `:WikiJournal`. Other times, I'll want to recall previous notes. For that, I use a slightly modified version of `:WikiPages` (it searches the body instead of the title only, I could probably integrate it with WikiPages but didn't have time yet).

That is to say: To me, being able to jump into the journal/wiki from anywhere is a really useful feature. 

Now, before looking into the code, I did not know about "local roots". They might be useful! I just didn't even them in my mental model :)

That said, I think here the choice is about the ergonomics of the tool. 
Yes, I can see a few dimensions (but I don't have enough data to make an informed decision):

- We could have banged version of each command, that either only consider the global setting or look for a local root.
- Which one would be the default (e.g., for mappings) might depend on whether users are using the local root or are being surprised by it (I am in the second bucket).
- Do we do it for all commands or only for journal ones? Here I'd be surprised as well if I was creating a new note (e.g. through a mapping from `WikiPages` and it ended up in the wrong directory). So I'd be for applying the same to all commands.

--- 

> First, you might be interested in the `g:wiki_global_load`. It should resolve your issue, although it would disable wiki.vim outside your `g:wiki_root` wiki.
> Now, I think we might want to consider this somewhat closer. I realize from your issue that it would make sense to load wiki.vim similar to the current default settings, but still let e.g. :WikiJournal navigate to your configured wiki/journal.

Exactly! I'd like to 1. keep the mappings; 2. be able to disable/override the "local behavior". 

One idea would be to have a more explicit wiki marker than `index.EXT`, e.g. `.local_wiki_root`.

> I think the first question here is if we should reconsider the behaviour of all of these commands or if the current behaviour is OK except for the journal?

I typically want `WikiPages` to open my global wiki, regardless of where I am. So I'd reconsider this for _all_ commands.

> Perhaps we should add banged variants to all of these, where a bang - e.g. :WikiJournal! - indicates that we should ignore the current local wiki and act on the globally defined wiki?

This could work! Would you default to the new or old behavior?

**Comment by lervag** [comment]
> Here's how I use `wiki.vim` (and I realize different users will do it differently). Sometimes, as I am coding/writing, I'll want to quickly take journal notes, or use the journal as a dated scratchpad. For that, I use `:WikiJournal`. Other times, I'll want to recall previous notes. For that, I use a slightly modified version of `:WikiPages` (it searches the body instead of the title only, I could probably integrate it with WikiPages but didn't have time yet).

This seems like a good workflow, thanks for sharing.

> That is to say: To me, being able to jump into the journal/wiki from anywhere is a really useful feature.

Yes, I agree. And that's also how I use it.

> Now, before looking into the code, I did not know about "local roots". They might be useful! I just didn't even them in my mental model :)

Heh, yes. The thing is, wiki.vim is sort of a "remake" of vimwiki. And a central concept in vimwiki is that you can define as many wikis as you want and you specify each of them in your config.

I started off thinking "I only want a single, global wiki". That worked well for a long while, but it sort of fails when you notice you are working on markdown projects that are really wikis of their own. Thus I needed to reconsider how the global commands such as `:WikiIndex` and so on worked. And without putting too much thought into it I ended up making the current behaviour: All global commands will act on either 1) the current local wiki, if one is detected, or 2) the globally defined wiki (`g:wiki_root`).

Now, after some time someone reported that they didn't like this behaviour, so I made `g:wiki_global_load`. I now realize that this was probably not really a good solution.

> One idea would be to have a more explicit wiki marker than `index.EXT`, e.g. `.local_wiki_root`.

I did not quite understand this - could you elaborate?

> > Perhaps we should add banged variants to all of these, where a bang - e.g. :WikiJournal! - indicates that we should ignore the current local wiki and act on the globally defined wiki?
> 
> This could work! Would you default to the new or old behavior?

I think I would make the default use the global wiki as the target and the banged versions would behave as the _current_ versions do (i.e. local if it exists, else global).

This would be a breaking change, but I believe it will align with the expected behaviour (even for myself).

Does this mean I can conclude that a good solution for this issue is to:

1. Adjust the current behaviour of the global wiki commands to, by default, always act on the globally specified `g:wiki_root`.
2. Make banged variants of the same commands that behave as the _current_ versions do.

**Comment by lervag** [comment]
I've implemented the solution I suggested now, please update and test. I would also be happy to get some feedback to the updated docs on the commands, i.e. `:help WikiIndex` and so on.
