### ISSUE TITLE
Automatically generating a journal index file.

### ISSUE THREAD

**Issue by skervim** [lervag/wiki.vim#47]
What is the recommended workflow to maintain an index file for the journal? 
In `vimwiki` there is `:VimwikiDiaryGenerateLinks` (mapped to `<Leader>w<Leader>i`) that allows to easily generate and update an index file of the diary. 

I saw that  `wiki.vim` has `:WikiJournalIndex`. However, it only seems to work with the `wiki` and not the `markdown` syntax and most importantly it does not update an index file but adds the index to the current file.  

So currently I would need to create an index file, open it and call `:WikiJournalIndex` to create the index. Then, when I write a new diary, I would have to open the file again, remove the content and call `:WikiJournalIndex` again. Is there a simpler way?

**Comment by lervag** [comment]
Currently, no. Sorry. The reason is that I never really needed this feature. I kept a simple version, as you've noticed, but it does not work so smoothly as you probably want.

I could probably improve this. But first, I would challenge you once: is there really any value in this feature? That is, why do you need it; what does it give that other methods do not do better? E.g., for quickly finding diary/journal entries, I think it is better to use something like fzf.vim, ctrlp.vim, or similar. One can also quite easily browse the files in a terminal.

But, I will not be so hard to convince. If you still think the feature is important, then let's first describe it well so that I can write some good tests for it. A good specification makes the implementation much easier.

**Comment by gauteh** [comment]
I have previously used the `vim-calendar` plugin to achieve something similar, but I find myself creating a temporary buffer with WikiJournalIndex often to get a concise list of journal-entries (partly because the calender plugin is a bit slow, and hard to see which days there exist an entry for). Whatever file generated by this command will be outdated next time I need it.

(thanks for this plugin!)

**Comment by skervim** [comment]
> Currently, no. Sorry. The reason is that I never really needed this feature. I kept a simple version, as you've noticed, but it does not work so smoothly as you probably want.
> 
> I could probably improve this. But first, I would challenge you once: is there really any value in this feature? That is, why do you need it; what does it give that other methods do not do better? E.g., for quickly finding diary/journal entries, I think it is better to use something like fzf.vim, ctrlp.vim, or similar. One can also quite easily browse the files in a terminal.
> 
> But, I will not be so hard to convince. If you still think the feature is important, then let's first describe it well so that I can write some good tests for it. A good specification makes the implementation much easier.

Ok, I think you might be right. Thanks for your reply. :)

**Comment by lervag** [comment]
> @gauteh I have previously used the vim-calendar plugin to achieve something similar, but I find myself creating a temporary buffer with `WikiJournalIndex` often to get a concise list of journal-entries (partly because the calender plugin is a bit slow, and hard to see which days there exist an entry for). Whatever file generated by this command will be outdated next time I need it.

I'm sorry for being daft, but I'm not quite sure what your point is.

I also use `vim-calendar`. If I knew how, I would be happy to add some code to couple it so that it would be possible to highlight dates in the calendar where there are diary/journal entries.

Personally, if I need a list of journal-entries, I simply use a terminal and list them manually. Since I use iso dates, I trivially get a nice and sorted list of dates.

> (thanks for this plugin!)

I'm happy you like it, and thanks for pitching in!

> @skervim Ok, I think you might be right. Thanks for your reply. :)

No problem! As mentioned, though, I would not really mind to make improvements to the existing command. You mention two main shortcomings:
1. A fixed syntax for the entry links (`wiki` format).
2. Inability to update an existing index.

Is this correctly understood by me? The first one should be quite simple to fix. The second one might be harder, but I could try. I can't promise it is fixed very fast, but I'll keep the issue open until I give it a try.

**Comment by gauteh** [comment]
Yes, I should try using the terminal, or maybe ranger for getting an overview.

**Comment by lervag** [comment]
Ok, I've improved things a little bit now. The command should now respect your `g:wiki_link_target_type` option, and it should also at least try to respect your `g:wiki_journal.date_format.daily` setting (i.e. things should still work if you use a different format than the default).

It should not be too difficult to change the behaviour wrt deleting old lines and such, but I am not sure I want to update that. For now, it should be quite simple to delete an old index and insert a new, if wanted, with this command. It should also be easily automated if one knows a little bit of vimscript.

So, I'll close this issue for now. If more people want me to work more on this future then I'll consider it.
