### ISSUE TITLE
Top-centered view on link follow

### ISSUE THREAD

**Issue by wailmerpailmer** [lervag/wiki.vim#49]
https://github.com/lervag/wiki.vim/blob/0f0556ba155914b924957cc04cd5270e88aee139/autoload/wiki/url/wiki.vim#L90

If a user has their vim setup configured to remember the previous line in a file, a top-centered view makes little sense, because it obscures information above the remembered line upon reentering a buffer.

It is very easy for a user to reinstate this feature to their liking:

`au BufWinEnter *.wiki exec "normal! zt"`

Though the above code does not work to override the plugin's centering unless one removes it manually from their local copy.

All considered, it seems better to leave the orientation of the window after following a link up to the user.

**Comment by lervag** [comment]
Yes, I agree. That line was added due to my own preference. What do you think about the part just above that focuses the folds? I like it and think it should do what most people expect, but not sure.

I think the solution to this issue is to add a User autocommand to allow people to execute some code whenever a link has been opened. This allows me to do `normal! zt`, and other people can do whatever they want.

The `BufWinEnter` autocommand would not work, I think, because it would trigger more often than when activating a link.

**Comment by wailmerpailmer** [comment]
Since the user can set what happens when a link is open, having the open link function still handle unfolding might cause confusion. Perhaps changing the view and unfolding should be set as defaults that the user can override with the WikiLinkOpened autocommand?

**Comment by lervag** [comment]
> might cause confusion

Yes, but it seems it does not, as I've not heard anything of it. If it does, and if anyone complains, then I will be glad to discuss it. But for now, I think I'm satisfied with the current behaviour. Or do you strongly disagree?
