### ISSUE TITLE
Citation links

### ISSUE THREAD

**Issue by jabirali** [lervag/wiki.vim#61]
Pandoc Markdown [supports citations](https://pandoc.org/MANUAL.html#citations) with the `pandoc-citeproc` extension, which works via the following basic syntax. For a citekey `ouassou2018`, the text `@ouassou2018 did some stuff [@ouassou2018]` would get translated to e.g. "Ouassou (2018) did some stuff (Ouassou, 2018)." Exactly how it is formatted of course depends on what options you use for the reference list (export format, reference format, etc.) The references can e.g. be provided via bibtex. As described in the link above, multiple citations can be combined using a semicolon; so `[@ouassou2018a; @ouassou2018b]` is interpreted as one citation of two sources. 

I think it would be interesting if the same syntax was supported in `wiki.vim`. Basically, we now have the syntax `[reference](zot:citekey)` available to cite entries in a Zotero database, which is useful. However, if you want to *export* parts of your wiki notes to some other format via `pandoc`, you currently have  to manually convert these citations to the `pandoc` format. All the information is already there - it's just in a different and incompatible format. Also, if you write some MarkDown for export with `pandoc`, and some private notes with `wiki.vim`, having to switch between two different syntaxes for MarkDown citations is perhaps not ideal.

The simplest implementation would probably be to just add the `@citekey` format as a synonym for `[citekey](zot:citekey)`. But if you also add support for the bracket syntaxes `[@citekey]` and `[@citekey1; @citekey2]`, I think each citekey can be handled in the same way; so if you were to add support to `WikiLinkOpen` for `@citekey`, you just have to let it work also inside brackets as well.

I don't know how the code is setup, but the latter might require adding a rule that a link matching the regexp `\[@.*\]` is not considered a bottom-style link. (This could probably be combined with the heuristic suggested in another issue #59 regarding recognizing MarkDown checkboxes.)

**Comment by lervag** [comment]
Let me start by trying to explain how the links are implemented in wiki.vim. I've taken to distinguish between a link and a url. A link is the combination of a link text and a link url (which may be of several schemes). This is best explained by examples (see also `:help wiki-links`):

- `[text](url)` (markdown style links)
- `[[url|text]]` (wiki style links; the `|text` part is optional)
- `[target]` or `[text][target]` (reference style links)
  - this is followed by a `[target]: url` below the text
- `scheme:address` (url without link; is also detected as long as the scheme is included)

Note that the `scheme` part of the url is not necessary in the first three types of links. If it is not there, then the `wiki` scheme is assumed.

----

With that; my first thought is that the syntax `@citekey` could be implemented as a shortcut for an url specification, e.g. `@citekey` is synonymous to `zot:citekey`. This should not be too difficult to implement (that is, it should be easy). This would be similar to your proposal, except instead of `@citekey` implying `[citekey](zot:citekey)` it would only imply `zot:citekey`. I would make sure that it would still be detected as a free url, of course.

However, the bracketed form `[@citekey]` and `[@c1; @c2]` is worse, because it conflicts with the reference style link defined above. I think you might be right that this could be solved by ensuring that ampersands are not allowed in reference style links.

Thus, I think the following seems a sensible implementation route:

- [ ] Add support for `@citekey` as a synonym for `zot:citekey` type urls.
- [ ] Change reference style links so that the single bracket `[content]` is only valid if there are no ampersands in `content`.

Comments?

**Comment by jabirali** [comment]
Thanks for the explanation. I agree, that sounds like a good plan :).

Adding `@citekey` as a synonym for `zot:citekey` would already be "good enough" for my use:

- `@citekey` is less typing than `[@citekey]`, and I would use the simplest syntax for notes;
- Via your Zotero handler, we would presumably get omnicompletion and the PDF open function; 
- I anyway use references more as an active part of the text when writing notes than articles;
- We can export the wiki file via Pandoc, and the references should be readable and make sense;
- Changing e.g. `\citet` to `\cite` as a postprocessing step after Pandoc export is much less work than trying to change unrecognized `zot:` links to `\cite`.

Having `[@citekey1; @citekey2]` available would be a nice bonus feature if it's not too much work :). Implementing this, I think, would also be solved by your proposed solution for #59?

**Comment by lervag** [comment]
This should work now, both wrt. links and completion.

**Comment by jabirali** [comment]
Works great! Thanks for implementing this :)

**Comment by lervag** [comment]
My pleasure; seems useful to me as well :)

**Comment by alwc** [comment]
@lervag It seems if I use `@some-citekey-string` instead of `zot:some-citekey-string`, `wiki#url#zot#parse` doesn't seem to work properly.  

* For `@some-citekey-string`, echo `self.stripped` in `wiki#url#zot#parse` will return `ome` (i.e. missing the first character and the text at and after the first `-`). 
* For `zot:some-citekey-string`, echo `self.stripped` in `wiki#url#zot#parse` will return `some-citekey-string`

**Comment by lervag** [comment]
Thanks; should be fixed now. The allowed characters in the citekey is now alphanumeric and `-` and `_`. This seems like a safe and useful set.

I assume you've read the docs on the Zotero scheme in `:help wiki-links-urls`? I've found that this feature works very well when I ensure `authorYear` style citekeys for my references. Omni completion also works very well when combined with `find` and `fd` (faster).

**Comment by alwc** [comment]
That's quick! Thanks @lervag 

> I've found that this feature works very well when I ensure authorYear style citekeys for my references.

Do you mean having something like `[auth:lower][year]` as your "Citation key format" under Zotero -> Preferences -> Better BibTeX -> Citation Keys?

**Comment by lervag** [comment]
> That's quick! Thanks @lervag

My pleasure :)

> Do you mean having something like [auth:lower][year] as your "Citation key format" under Zotero -> Preferences -> Better BibTeX -> Citation Keys?

Yes, precisely! I combine this with the Zotfile extension with filenames formatted as `%b - {%T - } {%t}`. When it is properly set up, I get nice autocompletion. I also have a simple shell function that uses fzf for quickly opening any pdf:

```sh
z() {
  pdf=$(fd -t f -e pdf . ~/.local/zotero | fzf -m -d '/' --with-nth=-1)
  if [ -f "$pdf" ]; then
    echo ${pdf#*zotero/storage/}
    zathura $pdf &
  fi
}
```

This relies on `fd` for finding the files and `fzf` for interactive choosing.

**Comment by alwc** [comment]
> > That's quick! Thanks @lervag
> 
> My pleasure :)
> 
> > Do you mean having something like [auth:lower][year] as your "Citation key format" under Zotero -> Preferences -> Better BibTeX -> Citation Keys?
> 
> Yes, precisely! I combine this with the Zotfile extension with filenames formatted as `%b - {%T - } {%t}`. When it is properly set up, I get nice autocompletion. I also have a simple shell function that uses fzf for quickly opening any pdf:
> 
> ```shell
> z() {
>   pdf=$(fd -t f -e pdf . ~/.local/zotero | fzf -m -d '/' --with-nth=-1)
>   if [ -f "$pdf" ]; then
>     echo ${pdf#*zotero/storage/}
>     zathura $pdf &
>   fi
> }
> ```
> 
> This relies on `fd` for finding the files and `fzf` for interactive choosing.

Nice! I think I'll make some modification of your script and create a new script with [`rga`](https://github.com/phiresky/ripgrep-all) so that I can search within PDFs too.

**Comment by lervag** [comment]
> Nice! I think I'll make some modification of your script and create a new script with [`rga`](https://github.com/phiresky/ripgrep-all) so that I can search within PDFs too.

I was not aware of `rga`. It seems interesting. Thanks for making me aware of it!
