### ISSUE TITLE
(wiki-link-toggle) problem

### ISSUE THREAD

**Issue by SAmpIR-Ser** [lervag/wiki.vim#72]
Just after I create a new wiki link `[[test]]`, I use the `<leader>wf` mapping to toggle the wiki style link,ie: `[[test]]`, to the markdown style link  `[test](test)`, the format is toggled successfully , BUT then, when I hit the link `[test](test)`, it enters the new file as `test.wiki` ,not as `test.md` which is suppoed to be as the format.

Any response/help will be much appreciated.

**Comment by lervag** [comment]
> Just after I create a new wiki link `[[test]]`, I use the `<leader>wf` mapping to toggle the wiki style link,ie: `[[test]]`, to the markdown style link  `[test](test)`, the format is toggled successfully , BUT then, when I hit the link `[test](test)`, it enters the new file as `test.wiki` ,not as `test.md` which is suppoed to be as the format.

The relevant options are:

```vim
" Set this to the list of filetypes you want to use. The first in the list is
" used as the default extension when opening wiki links.
let g:wiki_filetypes = ['md']

" If you want the Return to create markdown type links by default
let g:wiki_link_target_type = 'md'

" If you want the extensions to be explicit
let g:wiki_link_extension = '.md'
```

**Comment by nickwynja** [comment]
I'm running into this issue as well. Even with the following settings, `(wiki-link-toggle)` doesn't work quite as expected:

```vim
let g:wiki_filetypes = ['md']
let g:wiki_link_target_type = 'md'
let g:wiki_link_extension = '.md'
```
With these settings, creating a markdown link works as expected. I can have some text like `NewPage` and when I have the cursor over the text and hit `<cr>`, it creates a link like `[NewPage](NewPage.md)`.

If I have a link like `[[NewPage]]`, navigating works properly with `<cr>` but using `<leader>wf` turns `[[NewPage]]` into `[NewPage](NewPage)`. In this case, I'd expect it to take my `g:wiki_link_extension` setting.

Toggling from `[NewPage](NewPage.md)` results in `[[NewPage.md|NewPage]]`, which is not wrong but slightly unexpected since toggling from `[NewPage](NewPage)` returns `[[NewPage]]`. This result is ideal since in these cases the filename doesn't differ from the link name.

**Comment by lervag** [comment]
> If I have a link like `[[NewPage]]`, navigating works properly with `<cr>` but using `<leader>wf` turns `[[NewPage]]` into `[NewPage](NewPage)`. In this case, I'd expect it to take my `g:wiki_link_extension` setting.
>
> Toggling from `[NewPage](NewPage.md)` results in `[[NewPage.md|NewPage]]`, which is not wrong but slightly unexpected since toggling from `[NewPage](NewPage)` returns `[[NewPage]]`. This result is ideal since in these cases the filename doesn't differ from the link name.

If I understand correctly, the part you find unexpected is this:

1. `[[NewPage]]` + `<leader>wf` -> `[Newpage](NewPage)`

2. `[Newpage](NewPage.md)` + `<leader>wf` -> `[[NewPage.md|NewPage]]`

For me, this is expected, because this was how I implemented it. The option `g:wiki_link_extension` is used to add extension when creating a link from a word or selected text with `<cr>`. I never intended it to manipulate links when changing between wiki and markdown styles.

My impression is that a solution could be to allow a custom mappings/transformation when one toggles the link styles with `<leader>wf`. E.g. something like this (pseudocode):

```vim
let g:wiki_map_link_toggle = 'MyFunction'

function MyFunction(link) abort
  if a:link.target ==# 'wiki'
    let a:link.url = a:link.url - '.md'
  elseif a:link.target ==# 'md'
    let a:link.url = a:link.url + '.md'
  endif

  return a:link
endfunction
```

**Comment by nickwynja** [comment]
> If I understand correctly, the part you find unexpected is this:
> 
> 1. `[[NewPage]]` + `<leader>wf` -> `[Newpage](NewPage)`
> 2. `[Newpage](NewPage.md)` + `<leader>wf` -> `[[NewPage.md|NewPage]]`

Yes, that's correct.

> My impression is that a solution could be to allow a custom mappings/transformation when one toggles the link styles with `<leader>wf`.

I like this idea. I'm using custom functions for `g:wiki_map_create_page` and `g:wiki_map_link_create` and like this powerful customization.

Thank you for this great tool.

**Comment by lervag** [comment]
Ok, I made a quick implementation now. What do you think?

**Comment by nickwynja** [comment]
Great solution! I'm using the custom functions in combination with  `g:wiki_link_extension` and `SetWikiFilename` (the function I use for `g:wiki_map_create_page` and `g:wiki_map_link_create`) together to get to my desired output.

With the following settings:

```vim
let g:wiki_link_extension = '.md'
let g:wiki_map_create_page = 'SetWikiFilename'
let g:wiki_map_link_create = 'SetWikiFilename'
```
and this function:

```vim
function! SetWikiFilename(text) abort
    return substitute(a:text, '\s\+', '', 'g')
endfunction
```

I'm able to use `g:wiki_link_toggles` to build on what's in the docs:

```vim
function WikiToggleWiki(url, text) abort dict
    let l:url = SetWikiFilename(a:url)
    return wiki#link#md#template(l:url . g:wiki_link_extension,
                \ empty(a:text) ? a:url : a:text)
endfunction

function WikiToggleMd(url, text) abort dict
    let l:url = substitute(SetWikiFilename(a:url), g:wiki_link_extension, '', '')
    return wiki#link#wiki#template(l:url, a:text)
endfunction
```

The result of this for me is the following transforms:

Initial | Result
-|-
`[[NewPage]]` |  `[NewPage](NewPage.md)`
`[NewPage](NewPage.md)` | `[[NewPage]]`
`[[New Page]]` | `[New Page](NewPage.md)`
`[New Page](NewPage.md)` | `[[NewPage\|New Page]]`

 Thanks again!

**Comment by lervag** [comment]
Great, happy to hear that it works! Let me know if you find any rough edges.
