### ISSUE TITLE
announce breaking change

### ISSUE THREAD

**Issue by jackielii** [lervag/wiki.vim#75]
Hi there,

Firstly thanks for a great plugin. I use it everyday.

I think you recently renamed `g:wiki_link_target_map` to `g:wiki_link_target`. It would be great if you can have a release process where you do breaking changes, so that your users get some notice!

Thanks again!

**Comment by lervag** [comment]
> Firstly thanks for a great plugin. I use it everyday.

Great, I'm happy to hear it! :)

> I think you recently renamed `g:wiki_link_target_map` to `g:wiki_link_target`. It would be great if you can have a release process where you do breaking changes, so that your users get some notice!

Ah, yes, sorry. I'm not really that good at the whole release and versioning stuff. I'm sorry for the breaking change. Do you have a suggestion for how to properly do this so that users can get notice?

In the meantime: The change I made was due to #67. I'm also changing it again now, so the right option name from now will be `g:wiki_map_link_create`, see #71.

**Comment by jackielii** [comment]
IMO, for breaking changes, make both option available, and a deprecation warning in the release log. This will give the users some notice to switch to new option.

To do a release, just switch to the release tag, and click new release button. It'll do a tag and let you fill in release log.

When I see something not working, I always go to this project's release log and see what's new.

Again, thanks for the plugin! :+1:

**Comment by lervag** [comment]
Sorry for the late response!

> IMO, for breaking changes, make both option available, and a deprecation warning in the release log. This will give the users some notice to switch to new option.

This seems reasonable, except it also seems to add to the maintenance burden. I think I'll settle for adding a verbose deprecation warning. I.e., if I rename an option or similar, I'll not simply rename/delete, I'll add a check for the old version and give a warning to make the user aware.

> To do a release, just switch to the release tag, and click new release button. It'll do a tag and let you fill in release log.

Seems simple enough. I'll test it on this project. I'll probably not have a very well thought out schedule for releasing, though. :p

> When I see something not working, I always go to this project's release log and see what's new.

Yes, I often do a similar thing for most projects. For Vim plugins, though, I rarely see this kind of attention to the development cycle. Probably because there's more people like me who are not so familiar with that style or practise. I don't know.

> Again, thanks for the plugin! +1

Happy you like it!

**Comment by lervag** [comment]
I'll close this issue with a link to the first release:
https://github.com/lervag/wiki.vim/releases/tag/v0.1
