### ISSUE TITLE
suggestion: use `gf` to follow links

### ISSUE THREAD

**Issue by gauteh** [lervag/wiki.vim#87]
While briefly reading https://github.com/fcpg/vim-waikiki I saw that `gf` is used to follow links, and this makes a lot of sense! Perhaps this should be added as default as well as Enter?

**Comment by lervag** [comment]
Perhaps. But note: `gf` is already an internal feature to open a file. Would such a map "break" anything?

Also, it is easy to customize (but this will remove the `<cr>` mapping):

```vim
let g:wiki_mappings_local = {
      \ '<plug>(wiki-link-open)': 'gf',
      \}
```

**Comment by gauteh** [comment]
True, don't want to mess up other functionality. I use the other mapping frequently, and thought that this use case felt analogous.

**Comment by lervag** [comment]
Yes, I can see what you mean. I am tempted to test it. But at least I've now added an event `WikiBufferInitialized` that you can use to override mappings. E.g.:

```vim
augroup MyWikiAutocmds
  autocmd!
  autocmd User WikiBufferInitialized nmap <buffer> gf <plug>(wiki-link-open)
augroup END
```

So: I'm still considering to add `gf` as a standard mapping.

**Comment by gauteh** [comment]
Ah great, that will be useful for some other maps I have that worked a bit
inconsistently.

lør. 18. jul. 2020, 09:39 skrev Karl Yngve Lervåg <notifications@github.com

**Comment by gauteh** [comment]
Is it possible to make it fallback to default behavior when not under link? Maybe I should check the docs for how vim figures out filenames it follows to

**Comment by lervag** [comment]
> Is it possible to make it fallback to default behavior when not under link? Maybe I should check the docs for how vim figures out filenames it follows to

Well, no, not really. Because the `<cr>` mapping from wiki.vim already has a fallback behaviour which is to create a link from the current word. I don't see how we can fallback to the `gf` behaviour. Except if it is possible to determine if the original `gf` would actually find an existing target. I'm not quite sure about that.

What do you think? Should we investigate further, or is the new event based customization enough, since it gives the possibility to apply the mapping manually?

**Comment by gauteh** [comment]
Event based is fine, close enough.

søn. 19. jul. 2020, 16:13 skrev Karl Yngve Lervåg <notifications@github.com

**Comment by lervag** [comment]
Great, thanks!
