### ISSUE TITLE
TOC incompatible with hashtag tagging.

### ISSUE THREAD

**Issue by dahe3141** [lervag/wiki.vim#92]
Using command `:WikiPageToc`
expected behavior
```markdown
*Contents*
* [header1](#header1)
  * [sub header](#header1#sub header)

# header1
#tag

## sub header

````

Observed behavior
```markdown
*Contents*
* [[#header1]]
* [[#tag]]
  * [[#tag#sub header|sub header]]

# header1
#tag

## sub header

````
There are two problems with this function.
1. hashtag tagging is misread as header
2. Created links are not in markdown format

vim.init
```vim
let g:wiki_root = '~/vimwiki'
let g:wiki_link_target_type = 'md'
let g:wiki_filetypes = ['md']
let g:wiki_link_extension = '.md'
let g:wiki_tags_format_pattern = '\v%(^|\s)#\zs[^# ]+'
```

**Comment by lervag** [comment]
Not so sure about this: `#Test` is a valid header. Why do you want to use `#tag` as the tag format instead of something else?

**Comment by dahe3141** [comment]
> Not so sure about this: `#Test` is a valid header. Why do you want to use `#tag` as the tag format instead of something else?

If that's the case. I guess its my own problem then. Thanks. Really enjoyed your work.

**Comment by lervag** [comment]
Happy to hear it! Note, I don't mean to say I'm not going to consider making any changes/fixes here, but I first need to be convinced it makes sense. For me, `#tag` looks like a header, so under which "rule" should we determine that it is not a header, but a tag?

If you don't have a good answer, then I propose to use a different syntax for tags. Either use the default (`:tag:`) or something else through the config option.

**Comment by dahe3141** [comment]
I think the problem really stems from slacking Markdown syntax. `:joy:` is a emoji in popular parser such as this :joy:.
`:tag:` needs to live in metadata. But I have daily journal of different ideas with different tags that goes right under some sub-headers. I'm also considering a feature that can pull text block under a header that contains a specified tag from all files into one buffer. This would be helpful to review similar ideas.
I'm actually using a custom ctags to store tags file in wiki_root, along with fzf.vim's `:Tags` command to search. This may works better in a long run comparing to caching all tags in a local dictionary. I'm not competent enough to say it is the case though. But with ctags, above feature can be done with fzf multi-select pipe into  bashscript.

**Comment by lervag** [comment]
Yes, let's close the issue. I think you can get the features you want just by defining a tag syntax that's unique and distinguished from other syntax. I mean, it can be anything, really. E.g. `%tag` or `£tag` or `¤tag` or `{tag}`, and so on. Just pick something that works for you.

I can see that `:...:` does conflict with emoji syntax. The more popular plugin Vimwiki uses the [same syntax for tags](https://github.com/vimwiki/vimwiki/blob/master/doc/vimwiki.txt#L1449), i.e. `:tag:`, which is why I've kept it here as well. The same holds for [orgmode](https://orgmode.org/guide/Tags.html), it seems. So I think it is a good suggestion to use this syntax.
