### ISSUE TITLE
Changing the filename does not update the links to this page for the let g:wiki_link_extension = '.md'

### ISSUE THREAD

**Issue by DubininDmitry** [lervag/wiki.vim#97]
wiki.vim full setting (create special directory for better understanding):

```vim
let g:wiki_root = '~/Documents/temp'
let g:wiki_filetypes = ['wiki', 'markdown', 'md']
let g:wiki_link_target_type = 'md'
let g:wiki_link_extension = '.md'
let g:wiki_tags_scan_num_lines = 20

"export settings
let g:wiki_export = {
      \ 'args' : '',
      \ 'from_format' : 'markdown',
      \ 'ext' : 'html',
      \ 'view' : v:false,
      \ 'output': fnamemodify(tempname(), ':h'),
      \}

" format links
let g:wiki_map_link_create = 'FormatLinks'

function FormatLinks(text) abort
  return substitute(a:text, '\s\+', '_', 'g')
endfunction
```

In directory `temp`, create 2 files:

1. `temp 1.md` (links verified):

    ```markdown
    # This is markdown link to temp 2.md:
    [temp 2](temp 2.md)

    # This is wiki link to temp 2.m
    [[temp 2.md]]
    ```

2. `temp 2.md`:

    ```
    some interesting text
    ```

Now, in `temp 2.md`, I use `:WikiPageRename`, then confirm rename file, then `temp 2 newtitle`. The following message appears:

![image](https://user-images.githubusercontent.com/8066458/94913326-979b2780-0498-11eb-9b60-cb9c5bf8226f.png)

Press Enter and my current filename updated:

![image](https://user-images.githubusercontent.com/8066458/94913416-c5806c00-0498-11eb-88f9-64ef3c1659c1.png)

And in filesystem:

![image](https://user-images.githubusercontent.com/8066458/94913455-d4671e80-0498-11eb-9b0a-d6f640125f27.png)

When I open `temp 1.md`, the links are not changed.

When I change the settings and comment out these lines:

```vim
"let g:wiki_link_target_type = 'md'
"let g:wiki_link_extension = '.md'
```

And change links in file 1 according to changed settings (without extention):

```markdown
# This is markdown link to temp 2.md:
[temp 2](temp 2)

# This is wiki link to temp 2.md
[[temp 2]]
```

And try again rename second file:

![image](https://user-images.githubusercontent.com/8066458/94920022-febed900-04a4-11eb-8b4a-e3fde5889274.png)

And all links updated in file 1:

![image](https://user-images.githubusercontent.com/8066458/94920077-1ac27a80-04a5-11eb-8728-057e650e48cc.png)

**I tried different options for changing the settings and links, and apparently the links are not updated if the settings set `let g:wiki_link_extension = '.md'` and if links has `.md` extention**. 

For better understanding, settings default

```vim
let g:wiki_link_target_type = 'md'
let g:wiki_link_extension = '.md'
```

in `temp 1.md` add more different links with and without `.md`

```markdown
# This is markdown link to temp 2.md:
[temp 2](temp 2.md) and [temp 2](temp 2)

# This is wiki link to temp 2.md
[[temp 2.md]] and [[temp 2]]
```

Update `temp 2.md` (we have now 4 links in file):

![image](https://user-images.githubusercontent.com/8066458/94921252-73931280-04a7-11eb-9bc5-f0a8450cbb45.png)

And changed links in `temp 1.md`

![image](https://user-images.githubusercontent.com/8066458/94921381-c1a81600-04a7-11eb-998a-ae0efb8dbd65.png)

I hope my examples are clear enough to understand the essence of the problem.

**Comment by lervag** [comment]
Thanks. Can you please be explicit about what you are trying to do? With explicit I _mean_ explicit, give me every details. E.g.:

* Open file: `vim myfile.md`
* Change file: `:WikiRename`?

Before I look into this I want to be sure I understand. So, please, update your original description with a step-by-step explicit description (and also respond so that I get a notification).

**Comment by DubininDmitry** [comment]
> Thanks. Can you please be explicit about what you are trying to do? With explicit I _mean_ explicit, give me every details. E.g.:
> 
>     * Open file: `vim myfile.md`
> 
>     * Change file: `:WikiRename`?
> 
> 
> Before I look into this I want to be sure I understand. So, please, update your original description with a step-by-step explicit description (and also respond so that I get a notification).

I have made the description as detailed as possible.

Thanks for your work!

**Comment by lervag** [comment]
> > Thanks. Can you please be explicit about what you are trying to do? With explicit I _mean_ explicit, give me every details. E.g.:
> > ```
> > * Open file: `vim myfile.md`
> > 
> > * Change file: `:WikiRename`?
> > ```
> > 
> > 
> > Before I look into this I want to be sure I understand. So, please, update your original description with a step-by-step explicit description (and also respond so that I get a notification).
> 
> I have made the description as detailed as possible.
> 
> Thanks for your work!

**Comment by lervag** [comment]
Before I make any major changes, I think it is a good idea to think about what we expect here. I think your observation is correct, that `g:wiki_link_extension` is the main relevant option. I think we want the following behaviour after `:WikiPageRename`:

1. By default, with empty `g:wiki_link_extension`: wiki links should not have any extensions, and any wiki links (`[[...]]`) and markdown links (`[...](...)`) linking to the current page should be updated.

2. If `g:wiki_link_extension = 'xxx'`, then the same holds, except that the links need to also have the proper extension (e.g. `xxx`). Thus, `[[test.xxx]]` would match a wiki page `test.xxx`, while `[[test]]` would _not_ match.

As far as I understand, number one above works as expected, while number two does not. I.e., it seems the problem here is a bug in which the option `g:wiki_link_extension` is not properly respected by `:WikiPageRename`.

Do you agree with my analysis here, or did I miss something?

**Comment by lervag** [comment]
Before I make any major changes, I think it is a good idea to think about what we expect here. I think your observation is correct, that `g:wiki_link_extension` is the main relevant option. I think we want the following behaviour after `:WikiPageRename`:

1. By default, with empty `g:wiki_link_extension`: wiki links should not have any extensions, and any wiki links (`[[...]]`) and markdown links (`[...](...)`) linking to the current page should be updated.

2. If `g:wiki_link_extension = 'xxx'`, then the same holds, except that the links need to also have the proper extension (e.g. `xxx`). Thus, `[[test.xxx]]` would match a wiki page `test.xxx`, while `[[test]]` would _not_ match.

As far as I understand, number one above works as expected, while number two does not. I.e., it seems the problem here is a bug in which the option `g:wiki_link_extension` is not properly respected by `:WikiPageRename`.

Do you agree with my analysis here, or did I miss something?

**Comment by DubininDmitry** [comment]
Yes, apparently it is. If no additional factors influence, then your conclusions are correct.

**Comment by lervag** [comment]
I think this should be fixed now. Please test.

**Comment by DubininDmitry** [comment]
Now it works according to the settings in VIM. Thanks!

**Comment by lervag** [comment]
Great, happy to hear it :)
